version: '3'

services:
  # 1. O Coletor de Dados
  prometheus:
    image: prom/prometheus:latest
    container_name: meu-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  # 2. O Visualizador (Dashboard)
  grafana:
    image: grafana/grafana:latest
    container_name: meu-grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus