global:
  scrape_interval: 15s # Coleta dados a cada 15 segundos

scrape_configs:
  - job_name: 'meu-monitor'
    static_configs:
      - targets: ['localhost:9090'] # O Prometheus vai se monitorar (apenas para teste)