name: Build e Publish Docker

on:
  - push

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Construir e Taggear
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/monitor-devops:latest .

      - name: Publicar (Push)
        run: docker push ${{ secrets.DOCKER_USERNAME }}/monitor-devops:latest
